In [1]:
import pandas as pd


df = pd.read_csv("nba.csv")


team = df.groupby('Team')


print(team.first())

                                         Name  Number Position   Age Height  \
Team
Atlanta Hawks                   Kent Bazemore    24.0       SF  26.0    6-5
Boston Celtics                  Avery Bradley     0.0       PG  25.0    6-2
Brooklyn Nets                Bojan Bogdanovic    44.0       SG  27.0    6-8
Charlotte Hornets               Nicolas Batum     5.0       SG  27.0    6-8
Chicago Bulls                Cameron Bairstow    41.0       PF  25.0    6-9
Cleveland Cavaliers       Matthew Dellavedova     8.0       PG  25.0    6-4
Dallas Mavericks              Justin Anderson     1.0       SG  22.0    6-6
Denver Nuggets                 Darrell Arthur     0.0       PF  28.0    6-9
Detroit Pistons                  Joel Anthony    50.0        C  33.0    6-9
Golden State Warriors         Leandro Barbosa    19.0       SG  33.0    6-3
Houston Rockets                  Trevor Ariza     1.0       SF  30.0    6-8
Indiana Pacers                    Lavoy Allen     5.0       PF  27.0    6-9
Los Angeles Clippers             Cole Aldrich    45.0        C  27.0   6-11
Los Angeles Lakers               Brandon Bass     2.0       PF  31.0    6-8
Memphis Grizzlies                Jordan Adams     3.0       SG  21.0    6-5
Miami Heat                         Chris Bosh     1.0       PF  32.0   6-11
Milwaukee Bucks         Giannis Antetokounmpo    34.0       SF  21.0   6-11
Minnesota Timberwolves        Nemanja Bjelica    88.0       PF  28.0   6-10
New Orleans Pelicans            Alexis Ajinca    42.0        C  28.0    7-2
New York Knicks                 Arron Afflalo     4.0       SG  30.0    6-5
Oklahoma City Thunder            Steven Adams    12.0        C  22.0    7-0
Orlando Magic                  Dewayne Dedmon     3.0        C  26.0    7-0
Philadelphia 76ers                Elton Brand    42.0       PF  37.0    6-9
Phoenix Suns                     Eric Bledsoe     2.0       PG  26.0    6-1
Portland Trail Blazers        Cliff Alexander    34.0       PF  20.0    6-8
Sacramento Kings                   Quincy Acy    13.0       SF  25.0    6-7
San Antonio Spurs           LaMarcus Aldridge    12.0       PF  30.0   6-11
Toronto Raptors               Bismack Biyombo     8.0        C  23.0    6-9
Utah Jazz                       Trevor Booker    33.0       PF  28.0    6-8
Washington Wizards              Alan Anderson     6.0       SG  33.0    6-6

                        Weight                College      Salary
Team
Atlanta Hawks            201.0           Old Dominion   2000000.0
Boston Celtics           180.0                  Texas   7730337.0
Brooklyn Nets            216.0         Oklahoma State   3425510.0
Charlotte Hornets        200.0  Virginia Commonwealth  13125306.0
Chicago Bulls            250.0             New Mexico    845059.0
Cleveland Cavaliers      198.0           Saint Mary's   1147276.0
Dallas Mavericks         228.0               Virginia   1449000.0
Denver Nuggets           235.0                 Kansas   2814000.0
Detroit Pistons          245.0                   UNLV   2500000.0
Golden State Warriors    194.0         North Carolina   2500000.0
Houston Rockets          215.0                   UCLA   8193030.0
Indiana Pacers           255.0                 Temple   4050000.0
Los Angeles Clippers     250.0                 Kansas   1100602.0
Los Angeles Lakers       250.0                    LSU   3000000.0
Memphis Grizzlies        209.0                   UCLA   1404600.0
Miami Heat               235.0           Georgia Tech  22192730.0
Milwaukee Bucks          222.0                Arizona   1953960.0
Minnesota Timberwolves   240.0             Louisville   3950001.0
New Orleans Pelicans     248.0             California   4389607.0
New York Knicks          210.0                   UCLA   8000000.0
Oklahoma City Thunder    255.0             Pittsburgh   2279040.0
Orlando Magic            245.0                    USC    947276.0
Philadelphia 76ers       254.0                   Duke    947276.0
Phoenix Suns             190.0               Kentucky  13500000.0
Portland Trail Blazers   240.0                 Kansas    525093.0
Sacramento Kings         240.0                 Baylor    981348.0
San Antonio Spurs        240.0                  Texas  19689000.0
Toronto Raptors          245.0               Missouri   2814000.0
Utah Jazz                228.0                Clemson   4775000.0
Washington Wizards       220.0         Michigan State   4000000.0

In [2]:
import pandas as pd


df = pd.read_csv("nba.csv")


grouping = df.groupby(['Team', 'Position'])

# Print first row from each group
print(grouping.first())

                                         Name  Number   Age Height  Weight  \
Team               Position
Atlanta Hawks      C               Al Horford    15.0  30.0   6-10   245.0
                   PF          Kris Humphries    43.0  31.0    6-9   235.0
                   PG         Dennis Schroder    17.0  22.0    6-1   172.0
                   SF           Kent Bazemore    24.0  26.0    6-5   201.0
                   SG        Tim Hardaway Jr.    10.0  24.0    6-6   205.0
...                                       ...     ...   ...    ...     ...
Washington Wizards C            Marcin Gortat    13.0  32.0   6-11   240.0
                   PF             Drew Gooden    90.0  34.0   6-10   250.0
                   PG          Ramon Sessions     7.0  30.0    6-3   190.0
                   SF            Jared Dudley     1.0  30.0    6-7   225.0
                   SG           Alan Anderson     6.0  33.0    6-6   220.0

                                          College      Salary
Team               Position
Atlanta Hawks      C                      Florida  12000000.0
                   PF                   Minnesota   1000000.0
                   PG                 Wake Forest   1763400.0
                   SF                Old Dominion   2000000.0
                   SG                    Michigan   1304520.0
...                                           ...         ...
Washington Wizards C         North Carolina State  11217391.0
                   PF                      Kansas   3300000.0
                   PG                      Nevada   2170465.0
                   SF              Boston College   4375000.0
                   SG              Michigan State   4000000.0

[149 rows x 7 columns]

In [3]:
import pandas as pd
df = pd.read_csv("nba.csv")
aggregated_data = df.groupby(['Team', 'Position']).agg(
   total_salary=('Salary', 'sum'),
   avg_salary=('Salary', 'mean'),
   player_count=('Name', 'count')
)
print(aggregated_data)

                             total_salary    avg_salary  player_count
Team               Position
Atlanta Hawks      C           22756250.0  7.585417e+06             3
                   PF          23952268.0  5.988067e+06             4
                   PG           9763400.0  4.881700e+06             2
                   SF           6000000.0  3.000000e+06             2
                   SG          10431032.0  2.607758e+06             4
...                                   ...           ...           ...
Washington Wizards C           24490429.0  8.163476e+06             3
                   PF          11300000.0  5.650000e+06             2
                   PG          18022415.0  9.011208e+06             2
                   SF          11158800.0  2.789700e+06             4
                   SG          11356992.0  2.839248e+06             4

[149 rows x 3 columns]

In [4]:
import pandas as pd
df = pd.read_csv("nba.csv")
df['Rank within Team'] = df.groupby('Team')['Salary'].transform(lambda x: x.rank(ascending=False))
print(df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary  Rank within Team
0                Texas  7730337.0               2.0
1            Marquette  6796117.0               4.0
2    Boston University        NaN               NaN
3        Georgia State  1148640.0              14.0
4                  NaN  5000000.0               5.0
..                 ...        ...               ...
453             Butler  2433333.0               8.0
454                NaN   900000.0              15.0
455                NaN  2900000.0               6.0
456             Kansas   947276.0              14.0
457                NaN        NaN               NaN

[458 rows x 10 columns]

In [5]:
import pandas as pd
df = pd.read_csv("nba.csv")
filtered_df = df.groupby('Team').filter(lambda x: x['Salary'].mean() >= 1000000)
print(filtered_df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

In [6]:
import pandas as pd


df1 = pd.read_csv("student.csv")
df2 = pd.read_csv("salary.csv")

merged_df = pd.merge(
    df1,
    df2,
    on='ID',
    how='inner'
)

print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [8]:
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [7]:
merged_df = pd.merge(df1, df2, on='ID', how='left')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [9]:
import pandas as pd


df1 = pd.read_csv("student.csv")
df2 = pd.read_csv("salary.csv")


merged_df = pd.merge(
    df1,
    df2,
    on='ID',
    how='inner'
)


print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [10]:
merged_df = pd.merge(df1, df2, on='ID', how='right')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [11]:
merged_df = pd.merge(df1, df2, on='ID', how='outer')
print(merged_df)

   ID    Name  Age  Gender  Salary
0   1     Raj   25    Male   25000
1   2  Sharma   42    Male   42500
2   3   Saroj   22  Female   22300
3   4    Raja   51    Male   51400
4   5   Kajal   26  Female   26800

In [14]:
df1['Country'] = ['USA', 'Canada', 'USA', 'Canada', 'USA']
df2['Country'] = ['USA', 'Canada', 'USA', 'Canada', 'Mexico']

# Merge on 'ID' and 'Country'
merged_df = pd.merge(df1, df2, on=['ID', 'Country'], how='inner')
print(merged_df)

   ID    Name  Age Country  Gender  Salary
0   1     Raj   25     USA    Male   25000
1   2  Sharma   42  Canada    Male   42500
2   3   Saroj   22     USA  Female   22300
3   4    Raja   51  Canada    Male   51400

In [15]:
df2.rename(columns={'ID': 'EmployeeID'}, inplace=True)

# Merge using different column names
merged_df = pd.merge(df1, df2, left_on='ID', right_on='EmployeeID', how='inner')
print(merged_df)

   ID    Name  Age Country_x  EmployeeID  Gender  Salary Country_y
0   1     Raj   25       USA           1    Male   25000       USA
1   2  Sharma   42    Canada           2    Male   42500    Canada
2   3   Saroj   22       USA           3  Female   22300       USA
3   4    Raja   51    Canada           4    Male   51400    Canada
4   5   Kajal   26       USA           5  Female   26800    Mexico

In [16]:
import pandas as pd

# creating a dataframe
df = pd.DataFrame({'A': ['John', 'Boby', 'Mina'],
                   'B': ['Masters', 'Graduate', 'Graduate'],
                   'C': [27, 23, 21]})

df

      A         B   C
0  John   Masters  27
1  Boby  Graduate  23
2  Mina  Graduate  21

In [18]:
df.pivot(index='A', columns='B', values='C')

B     Graduate  Masters
A
Boby      23.0      NaN
John       NaN     27.0
Mina      21.0      NaN

In [19]:
df.pivot(index='A', columns='B', values=['C', 'A'])

            C                A
B    Graduate Masters Graduate Masters
A
Boby       23     NaN     Boby     NaN
John      NaN      27      NaN    John
Mina       21     NaN     Mina     NaN

In [22]:
import pandas as pd

df = pd.DataFrame({
    'A': ['John', 'John', 'Mina'],
    'B': ['Masters', 'Masters', 'Graduate'],
    'C': [27, 23, 21]
})

result = df.pivot_table(index='A', columns='B', values='C')

print(result)

B     Graduate  Masters
A
John       NaN     25.0
Mina      21.0      NaN